# Generated by Django 3.1.4 on 2021-02-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('company_name', models.CharField(max_length=30)),
                ('operation_countries', models.CharField(max_length=40)),
                ('objective', models.CharField(max_length=40)),
                ('more_details_description', models.TextField()),
            ],
        ),
    ]
